group:
  # Dependabot in Python repos
  - files:
      - source: python/dependabot.yml
        dest: .github/dependabot.yml

    repos: |
      FollowTheProcess/pytoil
      FollowTheProcess/madonna

  # .gitignore in Python repos
  - files:
      - source: python/.gitignore
        dest: .gitignore

    repos: |
      FollowTheProcess/pytoil
      FollowTheProcess/madonna
      FollowTheProcess/python_copier

  # Pre-commit in python repos
  - files:
      - source: python/.pre-commit-config.yaml
        dest: .pre-commit-config.yaml

    repos: |
      FollowTheProcess/pytoil
      FollowTheProcess/madonna

  # Dependabot in Go repos
  - files:
      - source: go/dependabot.yml
        dest: .github/dependabot.yml

    repos: |
      FollowTheProcess/spok
      FollowTheProcess/tag
      FollowTheProcess/msg
      FollowTheProcess/goignore
      FollowTheProcess/collections
      FollowTheProcess/py
      FollowTheProcess/semver

  # .gitignore in Go repos
  - files:
      - source: go/.gitignore
        dest: .gitignore

    repos: |
      FollowTheProcess/spok
      FollowTheProcess/tag
      FollowTheProcess/msg
      FollowTheProcess/goignore
      FollowTheProcess/collections
      FollowTheProcess/py
      FollowTheProcess/semver

  # Common config across all GitHub repos
  - files:
      - source: github/
        dest: .github/

      - source: git/.gitattributes
        dest: .gitattributes

    repos: |
      FollowTheProcess/go_copier
      FollowTheProcess/rust_copier
      FollowTheProcess/python_copier
      FollowTheProcess/madonna
      FollowTheProcess/goignore
      FollowTheProcess/msg
      FollowTheProcess/py
      FollowTheProcess/spok
      FollowTheProcess/pytoil
      FollowTheProcess/tag
      FollowTheProcess/semver
      FollowTheProcess/collections
      FollowTheProcess/vscode-spok

# Copier templates
FollowTheProcess/python_copier:
  - source: python/.gitignore
    dest: project/.gitignore

  - source: python/.pre-commit-config.yaml
    dest: project/.pre-commit-config.yaml

  - source: git/.gitattributes
    dest: project/.gitattributes

FollowTheProcess/go_copier:
  - source: go/.gitignore
    dest: project/.gitignore

  - source: git/.gitattributes
    dest: project/.gitattributes

FollowTheProcess/rust_copier:
  - source: rust/.gitignore
    dest: project/.gitignore

  - source: git/.gitattributes
    dest: project/.gitattributes
