name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_PREFIX: "Sync: "
          DRY_RUN: true # For now, when it works move it to the release step below
          REVIEWERS: FollowTheProcess

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write

  #   # Only release on new tag
  #   if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Run GitHub File Sync
  #       uses: BetaHuhn/repo-file-sync-action@v1
  #       with:
  #         GH_PAT: ${{ secrets.GH_PAT }}
  #         COMMIT_PREFIX: "Sync: "
  #         DRY_RUN: true # For now
  #         REVIEWERS: FollowTheProcess

  #     - name: Create GitHub Release
  #       uses: softprops/action-gh-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GITHUB_REPOSITORY: ${{ github.repository }}
  #       with:
  #         draft: false
  #         prerelease: false
